---

- name: database server is running
  hosts: all
  vars:
    database_pkgs:
    - mariadb-server
    - python3-PyMySQL

  tasks:
  - name: packages installed
    yum:
      name: "{{ item }}"
      state: present
    loop: "{{ database_pkgs }}"
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

  - name: start db service
    service:
      name: mariadb
      state: started
      enabled: true
    when: ansible_distribution == "CentOS"
    notify:
      - set db password

  handlers:
  - name: set db password
    mysql_user:
      name: root
      password: password

...
